#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jun 01 04:04:06 ART 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Sildur's Enhanced Default v1.172 Fancy.zip
